---

- name: Install Cassandra cluster
  gather_facts: true
  user: root
  hosts: cassandra
  roles:
    - role: ansible-role-java
    - role: ansible-cassandra
      cassandra_hosts: '{{ groups["cassandra"] }}'
