---

- name: Install Zookeeper cluster
  gather_facts: true
  user: root
  hosts: zookeeper
  roles:
    - role: ansible-role-java 
    - role: ansible-zookeeper
      zookeeper_hosts: '{{ groups["zookeeper"] }}'
  vars_files:
    - /opt/openstack-ansible-midonet/vars/all.yml
